### ISSUE TITLE
Configuration server

### ISSUE THREAD

**Issue by bvenceslas** [VBL-Limited/suluhisho#4]
- [x] Installer les utilitaires necessaires

- [x] setup backend

- [x] add modules

- [x] create user model

**Comment by Brackleycassinga** [comment]
Ticket 

- #4 I think we should consider using mongoDb and aws or firebase for auth?

What do you think ?
- We can have a conversation on this tomorrow if you are free.

**Comment by bvenceslas** [comment]
Good!
